pub mod protocol;
pub mod allowlist;
pub mod config;
pub mod logging;
pub mod webex;
pub mod slack;
pub mod discord;
pub mod irc;
pub mod platform;
pub mod sender;
pub mod router_bot;
pub mod receiver;
pub mod listener;

pub use protocol::{ECHO_PREFIX, format_echo, parse_echo, is_echo, format_response, parse_response};
pub use allowlist::Allowlist;
pub use config::{SenderConfig, BotConfig, ReceiverConfig};
pub use logging::{get_logger, NdjsonLogger, NoopLogger, WgrokLogger};
pub use webex::{send_message, send_card, get_message, get_attachment_action, extract_cards, ADAPTIVE_CARD_CONTENT_TYPE, _set_messages_url, _set_attachment_actions_url};
pub use slack::{send_message as slack_send_message, send_card as slack_send_card, _set_slack_url};
pub use discord::{send_message as discord_send_message, send_card as discord_send_card, _set_discord_api_base};
pub use irc::{IrcParams, parse_connection_string, send_message as irc_send_message, send_card as irc_send_card};
pub use platform::{platform_send_message, platform_send_card};
pub use sender::WgrokSender;
pub use router_bot::WgrokRouterBot;
pub use receiver::WgrokReceiver;
pub use listener::{IncomingMessage, MessageCallback, PlatformListener, create_listener};
